<?php

namespace Database\Seeders;

use App\Models\Municipality;
use Illuminate\Database\Seeder;

class MunicipalitiesSeeder extends Seeder
{

    private $municipalitys;

    public function __construct()
    {
        /*
            set the default seeds array municipalitys and id departament
        */

        $this->municipalitys = [

            ['name' => 'Medellin', 'departament_Id' => 1],
            ['name' => 'Abejorral', 'departament_Id' => 1],
            ['name' => 'Abriaqui', 'departament_Id' => 1],
            ['name' => 'Alejandria', 'departament_Id' => 1],
            ['name' => 'Amaga', 'departament_Id' => 1],
            ['name' => 'Amalfi', 'departament_Id' => 1],
            ['name' => 'Andes', 'departament_Id' => 1],
            ['name' => 'Angelopolis', 'departament_Id' => 1],
            ['name' => 'Angostura', 'departament_Id' => 1],
            ['name' => 'Anori', 'departament_Id' => 1],
            ['name' => 'Santafe De Antioquia', 'departament_Id' => 1],
            ['name' => 'Anza', 'departament_Id' => 1],
            ['name' => 'Apartado', 'departament_Id' => 1],
            ['name' => 'Arboletes', 'departament_Id' => 1],
            ['name' => 'Argelia', 'departament_Id' => 1],
            ['name' => 'Armenia', 'departament_Id' => 1],
            ['name' => 'Barbosa', 'departament_Id' => 1],
            ['name' => 'Belmira', 'departament_Id' => 1],
            ['name' => 'Bello', 'departament_Id' => 1],
            ['name' => 'Betania', 'departament_Id' => 1],
            ['name' => 'Betulia', 'departament_Id' => 1],
            ['name' => 'Ciudad Bolivar', 'departament_Id' => 1],
            ['name' => 'Briceño', 'departament_Id' => 1],
            ['name' => 'Buritica', 'departament_Id' => 1],
            ['name' => 'Caceres', 'departament_Id' => 1],
            ['name' => 'Caicedo', 'departament_Id' => 1],
            ['name' => 'Caldas', 'departament_Id' => 1],
            ['name' => 'Campamento', 'departament_Id' => 1],
            ['name' => 'Cañasgordas', 'departament_Id' => 1],
            ['name' => 'Caracoli', 'departament_Id' => 1],
            ['name' => 'Caramanta', 'departament_Id' => 1],
            ['name' => 'Carepa', 'departament_Id' => 1],
            ['name' => 'El Carmen De Viboral', 'departament_Id' => 1],
            ['name' => 'Carolina', 'departament_Id' => 1],
            ['name' => 'Caucasia', 'departament_Id' => 1],
            ['name' => 'Chigorodo', 'departament_Id' => 1],
            ['name' => 'Cisneros', 'departament_Id' => 1],
            ['name' => 'Cocorna', 'departament_Id' => 1],
            ['name' => 'Concepcion', 'departament_Id' => 1],
            ['name' => 'Concordia', 'departament_Id' => 1],
            ['name' => 'Copacabana', 'departament_Id' => 1],
            ['name' => 'Dabeiba', 'departament_Id' => 1],
            ['name' => 'Don Matias', 'departament_Id' => 1],
            ['name' => 'Ebejico', 'departament_Id' => 1],
            ['name' => 'El Bagre', 'departament_Id' => 1],
            ['name' => 'Entrerrios', 'departament_Id' => 1],
            ['name' => 'Envigado', 'departament_Id' => 1],
            ['name' => 'Fredonia', 'departament_Id' => 1],
            ['name' => 'Frontino', 'departament_Id' => 1],
            ['name' => 'Giraldo', 'departament_Id' => 1],
            ['name' => 'Girardota', 'departament_Id' => 1],
            ['name' => 'Gomez Plata', 'departament_Id' => 1],
            ['name' => 'Granada', 'departament_Id' => 1],
            ['name' => 'Guadalupe', 'departament_Id' => 1],
            ['name' => 'Guarne', 'departament_Id' => 1],
            ['name' => 'Guatape', 'departament_Id' => 1],
            ['name' => 'Heliconia', 'departament_Id' => 1],
            ['name' => 'Hispania', 'departament_Id' => 1],
            ['name' => 'Itagui', 'departament_Id' => 1],
            ['name' => 'Ituango', 'departament_Id' => 1],
            ['name' => 'Jardin', 'departament_Id' => 1],
            ['name' => 'Jerico', 'departament_Id' => 1],
            ['name' => 'La Ceja', 'departament_Id' => 1],
            ['name' => 'La Estrella', 'departament_Id' => 1],
            ['name' => 'La Pintada', 'departament_Id' => 1],
            ['name' => 'La Union', 'departament_Id' => 1],
            ['name' => 'Liborina', 'departament_Id' => 1],
            ['name' => 'Maceo', 'departament_Id' => 1],
            ['name' => 'Marinilla', 'departament_Id' => 1],
            ['name' => 'Montebello', 'departament_Id' => 1],
            ['name' => 'Murindo', 'departament_Id' => 1],
            ['name' => 'Mutata', 'departament_Id' => 1],
            ['name' => 'Nariño', 'departament_Id' => 1],
            ['name' => 'Necocli', 'departament_Id' => 1],
            ['name' => 'Nechi', 'departament_Id' => 1],
            ['name' => 'Olaya', 'departament_Id' => 1],
            ['name' => 'Peðol', 'departament_Id' => 1],
            ['name' => 'Peque', 'departament_Id' => 1],
            ['name' => 'Pueblorrico', 'departament_Id' => 1],
            ['name' => 'Puerto Berrio', 'departament_Id' => 1],
            ['name' => 'Puerto Nare', 'departament_Id' => 1],
            ['name' => 'Puerto Triunfo', 'departament_Id' => 1],
            ['name' => 'Remedios', 'departament_Id' => 1],
            ['name' => 'Retiro', 'departament_Id' => 1],
            ['name' => 'Rionegro', 'departament_Id' => 1],
            ['name' => 'Sabanalarga', 'departament_Id' => 1],
            ['name' => 'Sabaneta', 'departament_Id' => 1],
            ['name' => 'Salgar', 'departament_Id' => 1],
            ['name' => 'San Andres De Cuerquia', 'departament_Id' => 1],
            ['name' => 'San Carlos', 'departament_Id' => 1],
            ['name' => 'San Francisco', 'departament_Id' => 1],
            ['name' => 'San Jeronimo', 'departament_Id' => 1],
            ['name' => 'San Jose De La Montaña', 'departament_Id' => 1],
            ['name' => 'San Juan De Uraba', 'departament_Id' => 1],
            ['name' => 'San Luis', 'departament_Id' => 1],
            ['name' => 'San Pedro', 'departament_Id' => 1],
            ['name' => 'San Pedro De Uraba', 'departament_Id' => 1],
            ['name' => 'San Rafael', 'departament_Id' => 1],
            ['name' => 'San Roque', 'departament_Id' => 1],
            ['name' => 'San Vicente', 'departament_Id' => 1],
            ['name' => 'Santa Barbara', 'departament_Id' => 1],
            ['name' => 'Santa Rosa De Osos', 'departament_Id' => 1],
            ['name' => 'Santo Domingo', 'departament_Id' => 1],
            ['name' => 'El Santuario', 'departament_Id' => 1],
            ['name' => 'Segovia', 'departament_Id' => 1],
            ['name' => 'Sonson', 'departament_Id' => 1],
            ['name' => 'Sopetran', 'departament_Id' => 1],
            ['name' => 'Tamesis', 'departament_Id' => 1],
            ['name' => 'Taraza', 'departament_Id' => 1],
            ['name' => 'Tarso', 'departament_Id' => 1],
            ['name' => 'Titiribi', 'departament_Id' => 1],
            ['name' => 'Toledo', 'departament_Id' => 1],
            ['name' => 'Turbo', 'departament_Id' => 1],
            ['name' => 'Uramita', 'departament_Id' => 1],
            ['name' => 'Urrao', 'departament_Id' => 1],
            ['name' => 'Valdivia', 'departament_Id' => 1],
            ['name' => 'Valparaiso', 'departament_Id' => 1],
            ['name' => 'Vegachi', 'departament_Id' => 1],
            ['name' => 'Venecia', 'departament_Id' => 1],
            ['name' => 'Vigia Del Fuerte', 'departament_Id' => 1],
            ['name' => 'Yali', 'departament_Id' => 1],
            ['name' => 'Yarumal', 'departament_Id' => 1],
            ['name' => 'Yolombo', 'departament_Id' => 1],
            ['name' => 'Yondo', 'departament_Id' => 1],
            ['name' => 'Zaragoza', 'departament_Id' => 1],
            ['name' => 'Barranquilla', 'departament_Id' => 2],
            ['name' => 'Baranoa', 'departament_Id' => 2],
            ['name' => 'Campo De La Cruz', 'departament_Id' => 2],
            ['name' => 'Candelaria', 'departament_Id' => 2],
            ['name' => 'Galapa', 'departament_Id' => 2],
            ['name' => 'Juan De Acosta', 'departament_Id' => 2],
            ['name' => 'Luruaco', 'departament_Id' => 2],
            ['name' => 'Malambo', 'departament_Id' => 2],
            ['name' => 'Manati', 'departament_Id' => 2],
            ['name' => 'Palmar De Varela', 'departament_Id' => 2],
            ['name' => 'Piojo', 'departament_Id' => 2],
            ['name' => 'Polonuevo', 'departament_Id' => 2],
            ['name' => 'Ponedera', 'departament_Id' => 2],
            ['name' => 'Puerto Colombia', 'departament_Id' => 2],
            ['name' => 'Repelon', 'departament_Id' => 2],
            ['name' => 'Sabanagrande', 'departament_Id' => 2],
            ['name' => 'Sabanalarga', 'departament_Id' => 2],
            ['name' => 'Santa Lucia', 'departament_Id' => 2],
            ['name' => 'Santo Tomas', 'departament_Id' => 2],
            ['name' => 'Soledad', 'departament_Id' => 2],
            ['name' => 'Suan', 'departament_Id' => 2],
            ['name' => 'Tubara', 'departament_Id' => 2],
            ['name' => 'Usiacuri', 'departament_Id' => 2],
            ['name' => 'Cartagena', 'departament_Id' => 3],
            ['name' => 'Achi', 'departament_Id' => 3],
            ['name' => 'Altos Del Rosario', 'departament_Id' => 3],
            ['name' => 'Arenal', 'departament_Id' => 3],
            ['name' => 'Arjona', 'departament_Id' => 3],
            ['name' => 'Arroyohondo', 'departament_Id' => 3],
            ['name' => 'Barranco De Loba', 'departament_Id' => 3],
            ['name' => 'Calamar', 'departament_Id' => 3],
            ['name' => 'Cantagallo', 'departament_Id' => 3],
            ['name' => 'Cicuco', 'departament_Id' => 3],
            ['name' => 'Cordoba', 'departament_Id' => 3],
            ['name' => 'Clemencia', 'departament_Id' => 3],
            ['name' => 'El Carmen De Bolivar', 'departament_Id' => 3],
            ['name' => 'El Guamo', 'departament_Id' => 3],
            ['name' => 'El Peñon', 'departament_Id' => 3],
            ['name' => 'Hatillo De Loba', 'departament_Id' => 3],
            ['name' => 'Magangue', 'departament_Id' => 3],
            ['name' => 'Mahates', 'departament_Id' => 3],
            ['name' => 'Margarita', 'departament_Id' => 3],
            ['name' => 'Maria La Baja', 'departament_Id' => 3],
            ['name' => 'Montecristo', 'departament_Id' => 3],
            ['name' => 'Mompos', 'departament_Id' => 3],
            ['name' => 'Norosi', 'departament_Id' => 3],
            ['name' => 'Morales', 'departament_Id' => 3],
            ['name' => 'Pinillos', 'departament_Id' => 3],
            ['name' => 'Regidor', 'departament_Id' => 3],
            ['name' => 'Rio Viejo', 'departament_Id' => 3],
            ['name' => 'San Cristobal', 'departament_Id' => 3],
            ['name' => 'San Estanislao', 'departament_Id' => 3],
            ['name' => 'San Fernando', 'departament_Id' => 3],
            ['name' => 'San Jacinto', 'departament_Id' => 3],
            ['name' => 'San Jacinto Del Cauca', 'departament_Id' => 3],
            ['name' => 'San Juan Nepomuceno', 'departament_Id' => 3],
            ['name' => 'San Martin De Loba', 'departament_Id' => 3],
            ['name' => 'San Pablo', 'departament_Id' => 3],
            ['name' => 'Santa Catalina', 'departament_Id' => 3],
            ['name' => 'Santa Rosa', 'departament_Id' => 3],
            ['name' => 'Santa Rosa Del Sur', 'departament_Id' => 3],
            ['name' => 'Simiti', 'departament_Id' => 3],
            ['name' => 'Soplaviento', 'departament_Id' => 3],
            ['name' => 'Talaigua Nuevo', 'departament_Id' => 3],
            ['name' => 'Tiquisio', 'departament_Id' => 3],
            ['name' => 'Turbaco', 'departament_Id' => 3],
            ['name' => 'Turbana', 'departament_Id' => 3],
            ['name' => 'Villanueva', 'departament_Id' => 3],
            ['name' => 'Zambrano', 'departament_Id' => 3],
            ['name' => 'Tunja', 'departament_Id' => 4],
            ['name' => 'Almeida', 'departament_Id' => 4],
            ['name' => 'Aquitania', 'departament_Id' => 4],
            ['name' => 'Arcabuco', 'departament_Id' => 4],
            ['name' => 'Belen', 'departament_Id' => 4],
            ['name' => 'Berbeo', 'departament_Id' => 4],
            ['name' => 'Beteitiva', 'departament_Id' => 4],
            ['name' => 'Boavita', 'departament_Id' => 4],
            ['name' => 'Boyaca', 'departament_Id' => 4],
            ['name' => 'Briceño', 'departament_Id' => 4],
            ['name' => 'Buenavista', 'departament_Id' => 4],
            ['name' => 'Busbanza', 'departament_Id' => 4],
            ['name' => 'Caldas', 'departament_Id' => 4],
            ['name' => 'Campohermoso', 'departament_Id' => 4],
            ['name' => 'Cerinza', 'departament_Id' => 4],
            ['name' => 'Chinavita', 'departament_Id' => 4],
            ['name' => 'Chiquinquira', 'departament_Id' => 4],
            ['name' => 'Chiscas', 'departament_Id' => 4],
            ['name' => 'Chita', 'departament_Id' => 4],
            ['name' => 'Chitaraque', 'departament_Id' => 4],
            ['name' => 'Chivata', 'departament_Id' => 4],
            ['name' => 'Cienega', 'departament_Id' => 4],
            ['name' => 'Combita', 'departament_Id' => 4],
            ['name' => 'Coper', 'departament_Id' => 4],
            ['name' => 'Corrales', 'departament_Id' => 4],
            ['name' => 'Covarachia', 'departament_Id' => 4],
            ['name' => 'Cubara', 'departament_Id' => 4],
            ['name' => 'Cucaita', 'departament_Id' => 4],
            ['name' => 'Cuitiva', 'departament_Id' => 4],
            ['Code' => '15232',  'name' => 'Chiquiza', 'departament_Id' => 4],
            ['name' => 'Chivor', 'departament_Id' => 4],
            ['name' => 'Duitama', 'departament_Id' => 4],
            ['name' => 'El Cocuy', 'departament_Id' => 4],
            ['name' => 'El Espino', 'departament_Id' => 4],
            ['name' => 'Firavitoba', 'departament_Id' => 4],
            ['name' => 'Floresta', 'departament_Id' => 4],
            ['name' => 'Gachantiva', 'departament_Id' => 4],
            ['name' => 'Gameza', 'departament_Id' => 4],
            ['name' => 'Garagoa', 'departament_Id' => 4],
            ['name' => 'Guacamayas', 'departament_Id' => 4],
            ['name' => 'Guateque', 'departament_Id' => 4],
            ['name' => 'Guayata', 'departament_Id' => 4],
            ['name' => 'Gsican', 'departament_Id' => 4],
            ['name' => 'Iza', 'departament_Id' => 4],
            ['name' => 'Jenesano', 'departament_Id' => 4],
            ['name' => 'Jerico', 'departament_Id' => 4],
            ['name' => 'Labranzagrande', 'departament_Id' => 4],
            ['name' => 'La Capilla', 'departament_Id' => 4],
            ['name' => 'La Victoria', 'departament_Id' => 4],
            ['name' => 'La Uvita', 'departament_Id' => 4],
            ['name' => 'Villa De Leyva', 'departament_Id' => 4],
            ['name' => 'Macanal', 'departament_Id' => 4],
            ['name' => 'Maripi', 'departament_Id' => 4],
            ['name' => 'Miraflores', 'departament_Id' => 4],
            ['name' => 'Mongua', 'departament_Id' => 4],
            ['name' => 'Mongui', 'departament_Id' => 4],
            ['name' => 'Moniquira', 'departament_Id' => 4],
            ['name' => 'Motavita', 'departament_Id' => 4],
            ['name' => 'Muzo', 'departament_Id' => 4],
            ['name' => 'Nobsa', 'departament_Id' => 4],
            ['name' => 'Nuevo Colon', 'departament_Id' => 4],
            ['name' => 'Oicata', 'departament_Id' => 4],
            ['name' => 'Otanche', 'departament_Id' => 4],
            ['name' => 'Pachavita', 'departament_Id' => 4],
            ['name' => 'Paez', 'departament_Id' => 4],
            ['name' => 'Paipa', 'departament_Id' => 4],
            ['name' => 'Pajarito', 'departament_Id' => 4],
            ['name' => 'Panqueba', 'departament_Id' => 4],
            ['name' => 'Pauna', 'departament_Id' => 4],
            ['name' => 'Paya', 'departament_Id' => 4],
            ['name' => 'Paz De Rio', 'departament_Id' => 4],
            ['name' => 'Pesca', 'departament_Id' => 4],
            ['name' => 'Pisba', 'departament_Id' => 4],
            ['name' => 'Puerto Boyaca', 'departament_Id' => 4],
            ['name' => 'Quipama', 'departament_Id' => 4],
            ['name' => 'Ramiriqui', 'departament_Id' => 4],
            ['name' => 'Raquira', 'departament_Id' => 4],
            ['name' => 'Rondon', 'departament_Id' => 4],
            ['name' => 'Saboya', 'departament_Id' => 4],
            ['name' => 'Sachica', 'departament_Id' => 4],
            ['name' => 'Samaca', 'departament_Id' => 4],
            ['name' => 'San Eduardo', 'departament_Id' => 4],
            ['name' => 'San Jose De Pare', 'departament_Id' => 4],
            ['name' => 'San Luis De Gaceno', 'departament_Id' => 4],
            ['name' => 'San Mateo', 'departament_Id' => 4],
            ['name' => 'San Miguel De Sema', 'departament_Id' => 4],
            ['name' => 'San Pablo De Borbur', 'departament_Id' => 4],
            ['name' => 'Santana', 'departament_Id' => 4],
            ['name' => 'Santa Maria', 'departament_Id' => 4],
            ['name' => 'Santa Rosa De Viterbo', 'departament_Id' => 4],
            ['name' => 'Santa Sofia', 'departament_Id' => 4],
            ['name' => 'Sativanorte', 'departament_Id' => 4],
            ['name' => 'Sativasur', 'departament_Id' => 4],
            ['name' => 'Siachoque', 'departament_Id' => 4],
            ['name' => 'Soata', 'departament_Id' => 4],
            ['name' => 'Socota', 'departament_Id' => 4],
            ['name' => 'Socha', 'departament_Id' => 4],
            ['name' => 'Sogamoso', 'departament_Id' => 4],
            ['name' => 'Somondoco', 'departament_Id' => 4],
            ['name' => 'Sora', 'departament_Id' => 4],
            ['name' => 'Sotaquira', 'departament_Id' => 4],
            ['name' => 'Soraca', 'departament_Id' => 4],
            ['name' => 'Susacon', 'departament_Id' => 4],
            ['name' => 'Sutamarchan', 'departament_Id' => 4],
            ['name' => 'Sutatenza', 'departament_Id' => 4],
            ['name' => 'Tasco', 'departament_Id' => 4],
            ['name' => 'Tenza', 'departament_Id' => 4],
            ['name' => 'Tibana', 'departament_Id' => 4],
            ['name' => 'Tibasosa', 'departament_Id' => 4],
            ['name' => 'Tinjaca', 'departament_Id' => 4],
            ['name' => 'Tipacoque', 'departament_Id' => 4],
            ['name' => 'Toca', 'departament_Id' => 4],
            ['name' => 'Togsi', 'departament_Id' => 4],
            ['name' => 'Topaga', 'departament_Id' => 4],
            ['name' => 'Tota', 'departament_Id' => 4],
            ['name' => 'Tunungua', 'departament_Id' => 4],
            ['name' => 'Turmeque', 'departament_Id' => 4],
            ['name' => 'Tuta', 'departament_Id' => 4],
            ['name' => 'Tutaza', 'departament_Id' => 4],
            ['name' => 'Umbita', 'departament_Id' => 4],
            ['name' => 'Ventaquemada', 'departament_Id' => 4],
            ['name' => 'Viracacha', 'departament_Id' => 4],
            ['name' => 'Zetaquira', 'departament_Id' => 4],
            ['name' => 'Manizales', 'departament_Id' => 5],
            ['name' => 'Aguadas', 'departament_Id' => 5],
            ['name' => 'Anserma', 'departament_Id' => 5],
            ['name' => 'Aranzazu', 'departament_Id' => 5],
            ['name' => 'Belalcazar', 'departament_Id' => 5],
            ['name' => 'Chinchina', 'departament_Id' => 5],
            ['name' => 'Filadelfia', 'departament_Id' => 5],
            ['name' => 'La Dorada', 'departament_Id' => 5],
            ['name' => 'La Merced', 'departament_Id' => 5],
            ['name' => 'Manzanares', 'departament_Id' => 5],
            ['name' => 'Marmato', 'departament_Id' => 5],
            ['name' => 'Marquetalia', 'departament_Id' => 5],
            ['name' => 'Marulanda', 'departament_Id' => 5],
            ['name' => 'Neira', 'departament_Id' => 5],
            ['name' => 'Norcasia', 'departament_Id' => 5],
            ['name' => 'Pacora', 'departament_Id' => 5],
            ['name' => 'Palestina', 'departament_Id' => 5],
            ['name' => 'Pensilvania', 'departament_Id' => 5],
            ['name' => 'Riosucio', 'departament_Id' => 5],
            ['name' => 'Risaralda', 'departament_Id' => 5],
            ['name' => 'Salamina', 'departament_Id' => 5],
            ['name' => 'Samana', 'departament_Id' => 5],
            ['name' => 'San Jose', 'departament_Id' => 5],
            ['name' => 'Supia', 'departament_Id' => 5],
            ['name' => 'Victoria', 'departament_Id' => 5],
            ['name' => 'Villamaria', 'departament_Id' => 5],
            ['name' => 'Viterbo', 'departament_Id' => 5],
            ['name' => 'Florencia', 'departament_Id' => 6],
            ['name' => 'Albania', 'departament_Id' => 6],
            ['name' => 'Belen De Los Andaquies', 'departament_Id' => 6],
            ['name' => 'Cartagena Del Chaira', 'departament_Id' => 6],
            ['name' => 'Curillo', 'departament_Id' => 6],
            ['name' => 'El Doncello', 'departament_Id' => 6],
            ['name' => 'El Paujil', 'departament_Id' => 6],
            ['name' => 'La Montañita', 'departament_Id' => 6],
            ['name' => 'Milan', 'departament_Id' => 6],
            ['name' => 'Morelia', 'departament_Id' => 6],
            ['name' => 'Puerto Rico', 'departament_Id' => 6],
            ['name' => 'San Jose Del Fragua', 'departament_Id' => 6],
            ['name' => 'San Vicente Del Caguan', 'departament_Id' => 6],
            ['name' => 'Solano', 'departament_Id' => 6],
            ['name' => 'Solita', 'departament_Id' => 6],
            ['name' => 'Valparaiso', 'departament_Id' => 6],
            ['name' => 'Popayan', 'departament_Id' => 7],
            ['name' => 'Almaguer', 'departament_Id' => 7],
            ['name' => 'Argelia', 'departament_Id' => 7],
            ['name' => 'Balboa', 'departament_Id' => 7],
            ['name' => 'Bolivar', 'departament_Id' => 7],
            ['name' => 'Buenos Aires', 'departament_Id' => 7],
            ['name' => 'Cajibio', 'departament_Id' => 7],
            ['name' => 'Caldono', 'departament_Id' => 7],
            ['name' => 'Caloto', 'departament_Id' => 7],
            ['name' => 'Corinto', 'departament_Id' => 7],
            ['name' => 'El Tambo', 'departament_Id' => 7],
            ['name' => 'Florencia', 'departament_Id' => 7],
            ['name' => 'Guachene', 'departament_Id' => 7],
            ['name' => 'Guapi', 'departament_Id' => 7],
            ['name' => 'Inza', 'departament_Id' => 7],
            ['name' => 'Jambalo', 'departament_Id' => 7],
            ['name' => 'La Sierra', 'departament_Id' => 7],
            ['name' => 'La Vega', 'departament_Id' => 7],
            ['name' => 'Lopez', 'departament_Id' => 7],
            ['name' => 'Mercaderes', 'departament_Id' => 7],
            ['name' => 'Miranda', 'departament_Id' => 7],
            ['name' => 'Morales', 'departament_Id' => 7],
            ['name' => 'Padilla', 'departament_Id' => 7],
            ['name' => 'Paez', 'departament_Id' => 7],
            ['name' => 'Patia', 'departament_Id' => 7],
            ['name' => 'Piamonte', 'departament_Id' => 7],
            ['name' => 'Piendamo', 'departament_Id' => 7],
            ['name' => 'Puerto Tejada', 'departament_Id' => 7],
            ['name' => 'Purace', 'departament_Id' => 7],
            ['name' => 'Rosas', 'departament_Id' => 7],
            ['name' => 'San Sebastian', 'departament_Id' => 7],
            ['name' => 'Santander De Quilichao', 'departament_Id' => 7],
            ['name' => 'Santa Rosa', 'departament_Id' => 7],
            ['name' => 'Silvia', 'departament_Id' => 7],
            ['name' => 'Sotara', 'departament_Id' => 7],
            ['name' => 'Suarez', 'departament_Id' => 7],
            ['name' => 'Sucre', 'departament_Id' => 7],
            ['name' => 'Timbio', 'departament_Id' => 7],
            ['name' => 'Timbiqui', 'departament_Id' => 7],
            ['name' => 'Toribio', 'departament_Id' => 7],
            ['name' => 'Totoro', 'departament_Id' => 7],
            ['name' => 'Villa Rica', 'departament_Id' => 7],
            ['name' => 'Valledupar', 'departament_Id' => 8],
            ['name' => 'Aguachica', 'departament_Id' => 8],
            ['name' => 'Agustin Codazzi', 'departament_Id' => 8],
            ['name' => 'Astrea', 'departament_Id' => 8],
            ['name' => 'Becerril', 'departament_Id' => 8],
            ['name' => 'Bosconia', 'departament_Id' => 8],
            ['name' => 'Chimichagua', 'departament_Id' => 8],
            ['name' => 'Chiriguana', 'departament_Id' => 8],
            ['name' => 'Curumani', 'departament_Id' => 8],
            ['name' => 'El Copey', 'departament_Id' => 8],
            ['name' => 'El Paso', 'departament_Id' => 8],
            ['name' => 'Gamarra', 'departament_Id' => 8],
            ['name' => 'Gonzalez', 'departament_Id' => 8],
            ['name' => 'La Gloria', 'departament_Id' => 8],
            ['name' => 'La Jagua De Ibirico', 'departament_Id' => 8],
            ['name' => 'Manaure', 'departament_Id' => 8],
            ['name' => 'Pailitas', 'departament_Id' => 8],
            ['name' => 'Pelaya', 'departament_Id' => 8],
            ['name' => 'Pueblo Bello', 'departament_Id' => 8],
            ['name' => 'Rio De Oro', 'departament_Id' => 8],
            ['name' => 'La Paz', 'departament_Id' => 8],
            ['name' => 'San Alberto', 'departament_Id' => 8],
            ['name' => 'San Diego', 'departament_Id' => 8],
            ['name' => 'San Martin', 'departament_Id' => 8],
            ['name' => 'Tamalameque', 'departament_Id' => 8],
            ['name' => 'Monteria', 'departament_Id' => 9],
            ['name' => 'Ayapel', 'departament_Id' => 9],
            ['name' => 'Buenavista', 'departament_Id' => 9],
            ['name' => 'Canalete', 'departament_Id' => 9],
            ['name' => 'Cerete', 'departament_Id' => 9],
            ['name' => 'Chima', 'departament_Id' => 9],
            ['name' => 'Chinu', 'departament_Id' => 9],
            ['name' => 'Cienaga De Oro', 'departament_Id' => 9],
            ['name' => 'Cotorra', 'departament_Id' => 9],
            ['name' => 'La Apartada', 'departament_Id' => 9],
            ['name' => 'Lorica', 'departament_Id' => 9],
            ['name' => 'Los Cordobas', 'departament_Id' => 9],
            ['name' => 'Momil', 'departament_Id' => 9],
            ['name' => 'Montelibano', 'departament_Id' => 9],
            ['name' => 'Moñitos', 'departament_Id' => 9],
            ['name' => 'Planeta Rica', 'departament_Id' => 9],
            ['name' => 'Pueblo Nuevo', 'departament_Id' => 9],
            ['name' => 'Puerto Escondido', 'departament_Id' => 9],
            ['name' => 'Puerto Libertador', 'departament_Id' => 9],
            ['name' => 'Purisima', 'departament_Id' => 9],
            ['name' => 'Sahagun', 'departament_Id' => 9],
            ['name' => 'San Andres Sotavento', 'departament_Id' => 9],
            ['name' => 'San Antero', 'departament_Id' => 9],
            ['name' => 'San Bernardo Del Viento', 'departament_Id' => 9],
            ['name' => 'San Carlos', 'departament_Id' => 9],
            ['name' => 'San Pelayo', 'departament_Id' => 9],
            ['name' => 'Tierralta', 'departament_Id' => 9],
            ['name' => 'Valencia', 'departament_Id' => 9],
            ['name' => 'Agua De Dios', 'departament_Id' => 10],
            ['name' => 'Alban', 'departament_Id' => 10],
            ['name' => 'Anapoima', 'departament_Id' => 10],
            ['name' => 'Anolaima', 'departament_Id' => 10],
            ['name' => 'Arbelaez', 'departament_Id' => 10],
            ['name' => 'Beltran', 'departament_Id' => 10],
            ['name' => 'Bituima', 'departament_Id' => 10],
            ['name' => 'Bogotá, D.C', 'departament_Id' => 10],
            ['name' => 'Bojaca', 'departament_Id' => 10],
            ['name' => 'Cabrera', 'departament_Id' => 10],
            ['name' => 'Cachipay', 'departament_Id' => 10],
            ['name' => 'Cajica', 'departament_Id' => 10],
            ['name' => 'Caparrapi', 'departament_Id' => 10],
            ['name' => 'Caqueza', 'departament_Id' => 10],
            ['name' => 'Carmen De Carupa', 'departament_Id' => 10],
            ['name' => 'Chaguani', 'departament_Id' => 10],
            ['name' => 'Chia', 'departament_Id' => 10],
            ['name' => 'Chipaque', 'departament_Id' => 10],
            ['name' => 'Choachi', 'departament_Id' => 10],
            ['name' => 'Choconta', 'departament_Id' => 10],
            ['name' => 'Cogua', 'departament_Id' => 10],
            ['name' => 'Cota', 'departament_Id' => 10],
            ['name' => 'Cucunuba', 'departament_Id' => 10],
            ['name' => 'El Colegio', 'departament_Id' => 10],
            ['name' => 'El Peñon', 'departament_Id' => 10],
            ['name' => 'El Rosal', 'departament_Id' => 10],
            ['name' => 'Facatativa', 'departament_Id' => 10],
            ['name' => 'Fomeque', 'departament_Id' => 10],
            ['name' => 'Fosca', 'departament_Id' => 10],
            ['name' => 'Funza', 'departament_Id' => 10],
            ['name' => 'Fuquene', 'departament_Id' => 10],
            ['name' => 'Fusagasuga', 'departament_Id' => 10],
            ['name' => 'Gachala', 'departament_Id' => 10],
            ['name' => 'Gachancipa', 'departament_Id' => 10],
            ['name' => 'Gacheta', 'departament_Id' => 10],
            ['name' => 'Gama', 'departament_Id' => 10],
            ['name' => 'Girardot', 'departament_Id' => 10],
            ['name' => 'Granada', 'departament_Id' => 10],
            ['name' => 'Guacheta', 'departament_Id' => 10],
            ['name' => 'Guaduas', 'departament_Id' => 10],
            ['name' => 'Guasca', 'departament_Id' => 10],
            ['name' => 'Guataqui', 'departament_Id' => 10],
            ['name' => 'Guatavita', 'departament_Id' => 10],
            ['name' => 'Guayabal De Siquima', 'departament_Id' => 10],
            ['name' => 'Guayabetal', 'departament_Id' => 10],
            ['name' => 'Gutierrez', 'departament_Id' => 10],
            ['name' => 'Jerusalen', 'departament_Id' => 10],
            ['name' => 'Junin', 'departament_Id' => 10],
            ['name' => 'La Calera', 'departament_Id' => 10],
            ['name' => 'La Mesa', 'departament_Id' => 10],
            ['name' => 'La Palma', 'departament_Id' => 10],
            ['name' => 'La Peña', 'departament_Id' => 10],
            ['name' => 'La Vega', 'departament_Id' => 10],
            ['name' => 'Lenguazaque', 'departament_Id' => 10],
            ['name' => 'Macheta', 'departament_Id' => 10],
            ['name' => 'Madrid', 'departament_Id' => 10],
            ['name' => 'Manta', 'departament_Id' => 10],
            ['name' => 'Medina', 'departament_Id' => 10],
            ['name' => 'Mosquera', 'departament_Id' => 10],
            ['name' => 'Nariño', 'departament_Id' => 10],
            ['name' => 'Nemocon', 'departament_Id' => 10],
            ['name' => 'Nilo', 'departament_Id' => 10],
            ['name' => 'Nimaima', 'departament_Id' => 10],
            ['name' => 'Nocaima', 'departament_Id' => 10],
            ['name' => 'Venecia', 'departament_Id' => 10],
            ['name' => 'Pacho', 'departament_Id' => 10],
            ['name' => 'Paime', 'departament_Id' => 10],
            ['name' => 'Pandi', 'departament_Id' => 10],
            ['name' => 'Paratebueno', 'departament_Id' => 10],
            ['name' => 'Pasca', 'departament_Id' => 10],
            ['name' => 'Puerto Salgar', 'departament_Id' => 10],
            ['name' => 'Puli', 'departament_Id' => 10],
            ['name' => 'Quebradanegra', 'departament_Id' => 10],
            ['name' => 'Quetame', 'departament_Id' => 10],
            ['name' => 'Quipile', 'departament_Id' => 10],
            ['name' => 'Apulo', 'departament_Id' => 10],
            ['name' => 'Ricaurte', 'departament_Id' => 10],
            ['name' => 'San Antonio Del Tequendama', 'departament_Id' => 10],
            ['name' => 'San Bernardo', 'departament_Id' => 10],
            ['name' => 'San Cayetano', 'departament_Id' => 10],
            ['name' => 'San Francisco', 'departament_Id' => 10],
            ['name' => 'San Juan De Rio Seco', 'departament_Id' => 10],
            ['name' => 'Sasaima', 'departament_Id' => 10],
            ['name' => 'Sesquile', 'departament_Id' => 10],
            ['name' => 'Sibate', 'departament_Id' => 10],
            ['name' => 'Silvania', 'departament_Id' => 10],
            ['name' => 'Simijaca', 'departament_Id' => 10],
            ['name' => 'Soacha', 'departament_Id' => 10],
            ['name' => 'Sopo', 'departament_Id' => 10],
            ['name' => 'Subachoque', 'departament_Id' => 10],
            ['name' => 'Suesca', 'departament_Id' => 10],
            ['name' => 'Supata', 'departament_Id' => 10],
            ['name' => 'Susa', 'departament_Id' => 10],
            ['name' => 'Sutatausa', 'departament_Id' => 10],
            ['name' => 'Tabio', 'departament_Id' => 10],
            ['name' => 'Tausa', 'departament_Id' => 10],
            ['name' => 'Tena', 'departament_Id' => 10],
            ['name' => 'Tenjo', 'departament_Id' => 10],
            ['name' => 'Tibacuy', 'departament_Id' => 10],
            ['name' => 'Tibirita', 'departament_Id' => 10],
            ['name' => 'Tocaima', 'departament_Id' => 10],
            ['name' => 'Tocancipa', 'departament_Id' => 10],
            ['name' => 'Topaipi', 'departament_Id' => 10],
            ['name' => 'Ubala', 'departament_Id' => 10],
            ['name' => 'Ubaque', 'departament_Id' => 10],
            ['name' => 'Villa De San Diego De Ubate', 'departament_Id' => 10],
            ['name' => 'Une', 'departament_Id' => 10],
            ['name' => 'Utica', 'departament_Id' => 10],
            ['name' => 'Vergara', 'departament_Id' => 10],
            ['name' => 'Viani', 'departament_Id' => 10],
            ['name' => 'Villagomez', 'departament_Id' => 10],
            ['name' => 'Villapinzon', 'departament_Id' => 10],
            ['name' => 'Villeta', 'departament_Id' => 10],
            ['name' => 'Viota', 'departament_Id' => 10],
            ['name' => 'Yacopi', 'departament_Id' => 10],
            ['name' => 'Zipacon', 'departament_Id' => 10],
            ['name' => 'Zipaquira', 'departament_Id' => 10],
            ['name' => 'Quibdo', 'departament_Id' => 11],
            ['name' => 'Acandi', 'departament_Id' => 11],
            ['name' => 'Alto Baudo', 'departament_Id' => 11],
            ['name' => 'Atrato', 'departament_Id' => 11],
            ['name' => 'Bagado', 'departament_Id' => 11],
            ['name' => 'Bahia Solano', 'departament_Id' => 11],
            ['name' => 'Bajo Baudo', 'departament_Id' => 11],
            ['name' => 'Bojaya', 'departament_Id' => 11],
            ['name' => 'El Canton Del San Pablo', 'departament_Id' => 11],
            ['name' => 'Carmen Del Darien', 'departament_Id' => 11],
            ['name' => 'Certegui', 'departament_Id' => 11],
            ['name' => 'Condoto', 'departament_Id' => 11],
            ['name' => 'El Carmen De Atrato', 'departament_Id' => 11],
            ['name' => 'El Litoral Del San Juan', 'departament_Id' => 11],
            ['name' => 'Istmina', 'departament_Id' => 11],
            ['name' => 'Jurado', 'departament_Id' => 11],
            ['name' => 'Lloro', 'departament_Id' => 11],
            ['name' => 'Medio Atrato', 'departament_Id' => 11],
            ['name' => 'Medio Baudo', 'departament_Id' => 11],
            ['name' => 'Medio San Juan', 'departament_Id' => 11],
            ['name' => 'Novita', 'departament_Id' => 11],
            ['name' => 'Nuqui', 'departament_Id' => 11],
            ['name' => 'Rio Iro', 'departament_Id' => 11],
            ['name' => 'Rio Quito', 'departament_Id' => 11],
            ['name' => 'Riosucio', 'departament_Id' => 11],
            ['name' => 'San Jose Del Palmar', 'departament_Id' => 11],
            ['name' => 'Sipi', 'departament_Id' => 11],
            ['name' => 'Tado', 'departament_Id' => 11],
            ['name' => 'Unguia', 'departament_Id' => 11],
            ['name' => 'Union Panamericana', 'departament_Id' => 11],
            ['name' => 'Neiva', 'departament_Id' => 12],
            ['name' => 'Acevedo', 'departament_Id' => 12],
            ['name' => 'Agrado', 'departament_Id' => 12],
            ['name' => 'Aipe', 'departament_Id' => 12],
            ['name' => 'Algeciras', 'departament_Id' => 12],
            ['name' => 'Altamira', 'departament_Id' => 12],
            ['name' => 'Baraya', 'departament_Id' => 12],
            ['name' => 'Campoalegre', 'departament_Id' => 12],
            ['name' => 'Colombia', 'departament_Id' => 12],
            ['name' => 'Elias', 'departament_Id' => 12],
            ['name' => 'Garzon', 'departament_Id' => 12],
            ['name' => 'Gigante', 'departament_Id' => 12],
            ['name' => 'Guadalupe', 'departament_Id' => 12],
            ['name' => 'Hobo', 'departament_Id' => 12],
            ['name' => 'Iquira', 'departament_Id' => 12],
            ['name' => 'Isnos', 'departament_Id' => 12],
            ['name' => 'La Argentina', 'departament_Id' => 12],
            ['name' => 'La Plata', 'departament_Id' => 12],
            ['name' => 'Nataga', 'departament_Id' => 12],
            ['name' => 'Oporapa', 'departament_Id' => 12],
            ['name' => 'Paicol', 'departament_Id' => 12],
            ['name' => 'Palermo', 'departament_Id' => 12],
            ['name' => 'Palestina', 'departament_Id' => 12],
            ['name' => 'Pital', 'departament_Id' => 12],
            ['name' => 'Pitalito', 'departament_Id' => 12],
            ['name' => 'Rivera', 'departament_Id' => 12],
            ['name' => 'Saladoblanco', 'departament_Id' => 12],
            ['name' => 'San Agustin', 'departament_Id' => 12],
            ['name' => 'Santa Maria', 'departament_Id' => 12],
            ['name' => 'Suaza', 'departament_Id' => 12],
            ['name' => 'Tarqui', 'departament_Id' => 12],
            ['name' => 'Tesalia', 'departament_Id' => 12],
            ['name' => 'Tello', 'departament_Id' => 12],
            ['name' => 'Teruel', 'departament_Id' => 12],
            ['name' => 'Timana', 'departament_Id' => 12],
            ['name' => 'Villavieja', 'departament_Id' => 12],
            ['name' => 'Yaguara', 'departament_Id' => 12],
            ['name' => 'Riohacha', 'departament_Id' => 13],
            ['name' => 'Albania', 'departament_Id' => 13],
            ['name' => 'Barrancas', 'departament_Id' => 13],
            ['name' => 'Dibulla', 'departament_Id' => 13],
            ['name' => 'Distraccion', 'departament_Id' => 13],
            ['name' => 'El Molino', 'departament_Id' => 13],
            ['name' => 'Fonseca', 'departament_Id' => 13],
            ['name' => 'Hatonuevo', 'departament_Id' => 13],
            ['name' => 'La Jagua Del Pilar', 'departament_Id' => 13],
            ['name' => 'Maicao', 'departament_Id' => 13],
            ['name' => 'Manaure', 'departament_Id' => 13],
            ['name' => 'San Juan Del Cesar', 'departament_Id' => 13],
            ['name' => 'Uribia', 'departament_Id' => 13],
            ['name' => 'Urumita', 'departament_Id' => 13],
            ['name' => 'Villanueva', 'departament_Id' => 13],
            ['name' => 'Santa Marta', 'departament_Id' => 14],
            ['name' => 'Algarrobo', 'departament_Id' => 14],
            ['name' => 'Aracataca', 'departament_Id' => 14],
            ['name' => 'Ariguani', 'departament_Id' => 14],
            ['name' => 'Cerro San Antonio', 'departament_Id' => 14],
            ['name' => 'Chibolo', 'departament_Id' => 14],
            ['name' => 'Cienaga', 'departament_Id' => 14],
            ['name' => 'Concordia', 'departament_Id' => 14],
            ['name' => 'El Banco', 'departament_Id' => 14],
            ['name' => 'El Piñon', 'departament_Id' => 14],
            ['name' => 'El Reten', 'departament_Id' => 14],
            ['name' => 'Fundacion', 'departament_Id' => 14],
            ['name' => 'Guamal', 'departament_Id' => 14],
            ['name' => 'Nueva Granada', 'departament_Id' => 14],
            ['name' => 'Pedraza', 'departament_Id' => 14],
            ['name' => 'Pijiño Del Carmen', 'departament_Id' => 14],
            ['name' => 'Pivijay', 'departament_Id' => 14],
            ['name' => 'Plato', 'departament_Id' => 14],
            ['name' => 'Puebloviejo', 'departament_Id' => 14],
            ['name' => 'Remolino', 'departament_Id' => 14],
            ['name' => 'Sabanas De San Angel', 'departament_Id' => 14],
            ['name' => 'Salamina', 'departament_Id' => 14],
            ['name' => 'San Sebastian De Buenavista', 'departament_Id' => 14],
            ['name' => 'San Zenon', 'departament_Id' => 14],
            ['name' => 'Santa Ana', 'departament_Id' => 14],
            ['name' => 'Santa Barbara De Pinto', 'departament_Id' => 14],
            ['name' => 'Sitionuevo', 'departament_Id' => 14],
            ['name' => 'Tenerife', 'departament_Id' => 14],
            ['name' => 'Zapayan', 'departament_Id' => 14],
            ['name' => 'Zona Bananera', 'departament_Id' => 14],
            ['name' => 'Villavicencio', 'departament_Id' => 15],
            ['name' => 'Acacias', 'departament_Id' => 15],
            ['name' => 'Barranca De Upia', 'departament_Id' => 15],
            ['name' => 'Cabuyaro', 'departament_Id' => 15],
            ['name' => 'Castilla La Nueva', 'departament_Id' => 15],
            ['name' => 'Cubarral', 'departament_Id' => 15],
            ['name' => 'Cumaral', 'departament_Id' => 15],
            ['name' => 'El Calvario', 'departament_Id' => 15],
            ['name' => 'El Castillo', 'departament_Id' => 15],
            ['name' => 'El Dorado', 'departament_Id' => 15],
            ['name' => 'Fuente De Oro', 'departament_Id' => 15],
            ['name' => 'Granada', 'departament_Id' => 15],
            ['name' => 'Guamal', 'departament_Id' => 15],
            ['name' => 'Mapiripan', 'departament_Id' => 15],
            ['name' => 'Mesetas', 'departament_Id' => 15],
            ['name' => 'La Macarena', 'departament_Id' => 15],
            ['name' => 'Uribe', 'departament_Id' => 15],
            ['name' => 'Lejanias', 'departament_Id' => 15],
            ['name' => 'Puerto Concordia', 'departament_Id' => 15],
            ['name' => 'Puerto Gaitan', 'departament_Id' => 15],
            ['name' => 'Puerto Lopez', 'departament_Id' => 15],
            ['name' => 'Puerto Lleras', 'departament_Id' => 15],
            ['name' => 'Puerto Rico', 'departament_Id' => 15],
            ['name' => 'Restrepo', 'departament_Id' => 15],
            ['name' => 'San Carlos De Guaroa', 'departament_Id' => 15],
            ['name' => 'San Juan De Arama', 'departament_Id' => 15],
            ['name' => 'San Juanito', 'departament_Id' => 15],
            ['name' => 'San Martin', 'departament_Id' => 15],
            ['name' => 'Vistahermosa', 'departament_Id' => 15],
            ['name' => 'Pasto', 'departament_Id' => 16],
            ['name' => 'Alban', 'departament_Id' => 16],
            ['name' => 'Aldana', 'departament_Id' => 16],
            ['name' => 'Ancuya', 'departament_Id' => 16],
            ['name' => 'Arboleda', 'departament_Id' => 16],
            ['name' => 'Barbacoas', 'departament_Id' => 16],
            ['name' => 'Belen', 'departament_Id' => 16],
            ['name' => 'Buesaco', 'departament_Id' => 16],
            ['name' => 'Colon', 'departament_Id' => 16],
            ['name' => 'Consaca', 'departament_Id' => 16],
            ['name' => 'Contadero', 'departament_Id' => 16],
            ['name' => 'Cordoba', 'departament_Id' => 16],
            ['name' => 'Cuaspud', 'departament_Id' => 16],
            ['name' => 'Cumbal', 'departament_Id' => 16],
            ['name' => 'Cumbitara', 'departament_Id' => 16],
            ['name' => 'Chachagsi', 'departament_Id' => 16],
            ['name' => 'El Charco', 'departament_Id' => 16],
            ['name' => 'El Peñol', 'departament_Id' => 16],
            ['name' => 'El Rosario', 'departament_Id' => 16],
            ['name' => 'El Tablon De Gomez', 'departament_Id' => 16],
            ['name' => 'El Tambo', 'departament_Id' => 16],
            ['name' => 'Funes', 'departament_Id' => 16],
            ['name' => 'Guachucal', 'departament_Id' => 16],
            ['name' => 'Guaitarilla', 'departament_Id' => 16],
            ['name' => 'Gualmatan', 'departament_Id' => 16],
            ['name' => 'Iles', 'departament_Id' => 16],
            ['name' => 'Imues', 'departament_Id' => 16],
            ['name' => 'Ipiales', 'departament_Id' => 16],
            ['name' => 'La Cruz', 'departament_Id' => 16],
            ['name' => 'La Florida', 'departament_Id' => 16],
            ['name' => 'La Llanada', 'departament_Id' => 16],
            ['name' => 'La Tola', 'departament_Id' => 16],
            ['name' => 'La Union', 'departament_Id' => 16],
            ['name' => 'Leiva', 'departament_Id' => 16],
            ['name' => 'Linares', 'departament_Id' => 16],
            ['name' => 'Los Andes', 'departament_Id' => 16],
            ['name' => 'Magsi', 'departament_Id' => 16],
            ['name' => 'Mallama', 'departament_Id' => 16],
            ['name' => 'Mosquera', 'departament_Id' => 16],
            ['name' => 'Nariño', 'departament_Id' => 16],
            ['name' => 'Olaya Herrera', 'departament_Id' => 16],
            ['name' => 'Ospina', 'departament_Id' => 16],
            ['name' => 'Francisco Pizarro', 'departament_Id' => 16],
            ['name' => 'Policarpa', 'departament_Id' => 16],
            ['name' => 'Potosi', 'departament_Id' => 16],
            ['name' => 'Providencia', 'departament_Id' => 16],
            ['name' => 'Puerres', 'departament_Id' => 16],
            ['name' => 'Pupiales', 'departament_Id' => 16],
            ['name' => 'Ricaurte', 'departament_Id' => 16],
            ['name' => 'Roberto Payan', 'departament_Id' => 16],
            ['name' => 'Samaniego', 'departament_Id' => 16],
            ['name' => 'Sandona', 'departament_Id' => 16],
            ['name' => 'San Bernardo', 'departament_Id' => 16],
            ['name' => 'San Lorenzo', 'departament_Id' => 16],
            ['name' => 'San Pablo', 'departament_Id' => 16],
            ['name' => 'San Pedro De Cartago', 'departament_Id' => 16],
            ['name' => 'Santa Barbara', 'departament_Id' => 16],
            ['name' => 'Santacruz', 'departament_Id' => 16],
            ['name' => 'Sapuyes', 'departament_Id' => 16],
            ['name' => 'Taminango', 'departament_Id' => 16],
            ['name' => 'Tangua', 'departament_Id' => 16],
            ['name' => 'San Andres De Tumaco', 'departament_Id' => 16],
            ['name' => 'Tuquerres', 'departament_Id' => 16],
            ['name' => 'Yacuanquer', 'departament_Id' => 16],
            ['name' => 'Cucuta', 'departament_Id' => 17],
            ['name' => 'Abrego', 'departament_Id' => 17],
            ['name' => 'Arboledas', 'departament_Id' => 17],
            ['name' => 'Bochalema', 'departament_Id' => 17],
            ['name' => 'Bucarasica', 'departament_Id' => 17],
            ['name' => 'Cacota', 'departament_Id' => 17],
            ['name' => 'Cachira', 'departament_Id' => 17],
            ['name' => 'Chinacota', 'departament_Id' => 17],
            ['name' => 'Chitaga', 'departament_Id' => 17],
            ['name' => 'Convencion', 'departament_Id' => 17],
            ['name' => 'Cucutilla', 'departament_Id' => 17],
            ['name' => 'Durania', 'departament_Id' => 17],
            ['name' => 'El Carmen', 'departament_Id' => 17],
            ['name' => 'El Tarra', 'departament_Id' => 17],
            ['name' => 'El Zulia', 'departament_Id' => 17],
            ['name' => 'Gramalote', 'departament_Id' => 17],
            ['name' => 'Hacari', 'departament_Id' => 17],
            ['name' => 'Herran', 'departament_Id' => 17],
            ['name' => 'Labateca', 'departament_Id' => 17],
            ['name' => 'La Esperanza', 'departament_Id' => 17],
            ['name' => 'La Playa', 'departament_Id' => 17],
            ['name' => 'Los Patios', 'departament_Id' => 17],
            ['name' => 'Lourdes', 'departament_Id' => 17],
            ['name' => 'Mutiscua', 'departament_Id' => 17],
            ['name' => 'Ocaña', 'departament_Id' => 17],
            ['name' => 'Pamplona', 'departament_Id' => 17],
            ['name' => 'Pamplonita', 'departament_Id' => 17],
            ['name' => 'Puerto Santander', 'departament_Id' => 17],
            ['name' => 'Ragonvalia', 'departament_Id' => 17],
            ['name' => 'Salazar', 'departament_Id' => 17],
            ['name' => 'San Calixto', 'departament_Id' => 17],
            ['name' => 'San Cayetano', 'departament_Id' => 17],
            ['name' => 'Santiago', 'departament_Id' => 17],
            ['name' => 'Sardinata', 'departament_Id' => 17],
            ['name' => 'Silos', 'departament_Id' => 17],
            ['name' => 'Teorama', 'departament_Id' => 17],
            ['name' => 'Tibu', 'departament_Id' => 17],
            ['name' => 'Toledo', 'departament_Id' => 17],
            ['name' => 'Villa Caro', 'departament_Id' => 17],
            ['name' => 'Villa Del Rosario', 'departament_Id' => 17],
            ['name' => 'Armenia', 'departament_Id' => 18],
            ['name' => 'Buenavista', 'departament_Id' => 18],
            ['name' => 'Calarca', 'departament_Id' => 18],
            ['name' => 'Circasia', 'departament_Id' => 18],
            ['name' => 'Cordoba', 'departament_Id' => 18],
            ['name' => 'Filandia', 'departament_Id' => 18],
            ['name' => 'Genova', 'departament_Id' => 18],
            ['name' => 'La Tebaida', 'departament_Id' => 18],
            ['name' => 'Montenegro', 'departament_Id' => 18],
            ['name' => 'Pijao', 'departament_Id' => 18],
            ['name' => 'Quimbaya', 'departament_Id' => 18],
            ['name' => 'Salento', 'departament_Id' => 18],
            ['name' => 'Pereira', 'departament_Id' => 19],
            ['name' => 'Apia', 'departament_Id' => 19],
            ['name' => 'Balboa', 'departament_Id' => 19],
            ['name' => 'Belen De Umbria', 'departament_Id' => 19],
            ['name' => 'Dosquebradas', 'departament_Id' => 19],
            ['name' => 'Guatica', 'departament_Id' => 19],
            ['name' => 'La Celia', 'departament_Id' => 19],
            ['name' => 'La Virginia', 'departament_Id' => 19],
            ['name' => 'Marsella', 'departament_Id' => 19],
            ['name' => 'Mistrato', 'departament_Id' => 19],
            ['name' => 'Pueblo Rico', 'departament_Id' => 19],
            ['name' => 'Quinchia', 'departament_Id' => 19],
            ['name' => 'Santa Rosa De Cabal', 'departament_Id' => 19],
            ['name' => 'Santuario', 'departament_Id' => 19],
            ['name' => 'Bucaramanga', 'departament_Id' => 20],
            ['name' => 'Aguada', 'departament_Id' => 20],
            ['name' => 'Albania', 'departament_Id' => 20],
            ['name' => 'Aratoca', 'departament_Id' => 20],
            ['name' => 'Barbosa', 'departament_Id' => 20],
            ['name' => 'Barichara', 'departament_Id' => 20],
            ['name' => 'Barrancabermeja', 'departament_Id' => 20],
            ['name' => 'Betulia', 'departament_Id' => 20],
            ['name' => 'Bolivar', 'departament_Id' => 20],
            ['name' => 'Cabrera', 'departament_Id' => 20],
            ['name' => 'California', 'departament_Id' => 20],
            ['name' => 'Capitanejo', 'departament_Id' => 20],
            ['name' => 'Carcasi', 'departament_Id' => 20],
            ['name' => 'Cepita', 'departament_Id' => 20],
            ['name' => 'Cerrito', 'departament_Id' => 20],
            ['name' => 'Charala', 'departament_Id' => 20],
            ['name' => 'Charta', 'departament_Id' => 20],
            ['name' => 'Chima', 'departament_Id' => 20],
            ['name' => 'Chipata', 'departament_Id' => 20],
            ['name' => 'Cimitarra', 'departament_Id' => 20],
            ['name' => 'Concepcion', 'departament_Id' => 20],
            ['name' => 'Confines', 'departament_Id' => 20],
            ['name' => 'Contratacion', 'departament_Id' => 20],
            ['name' => 'Coromoro', 'departament_Id' => 20],
            ['name' => 'Curiti', 'departament_Id' => 20],
            ['name' => 'El Carmen De Chucuri', 'departament_Id' => 20],
            ['name' => 'El Guacamayo', 'departament_Id' => 20],
            ['name' => 'El Peñon', 'departament_Id' => 20],
            ['name' => 'El Playon', 'departament_Id' => 20],
            ['name' => 'Encino', 'departament_Id' => 20],
            ['name' => 'Enciso', 'departament_Id' => 20],
            ['name' => 'Florian', 'departament_Id' => 20],
            ['name' => 'Floridablanca', 'departament_Id' => 20],
            ['name' => 'Galan', 'departament_Id' => 20],
            ['name' => 'Gambita', 'departament_Id' => 20],
            ['name' => 'Giron', 'departament_Id' => 20],
            ['name' => 'Guaca', 'departament_Id' => 20],
            ['name' => 'Guadalupe', 'departament_Id' => 20],
            ['name' => 'Guapota', 'departament_Id' => 20],
            ['name' => 'Guavata', 'departament_Id' => 20],
            ['name' => 'Güespa', 'departament_Id' => 20],
            ['name' => 'Hato', 'departament_Id' => 20],
            ['name' => 'Jesus Maria', 'departament_Id' => 20],
            ['name' => 'Jordan', 'departament_Id' => 20],
            ['name' => 'La Belleza', 'departament_Id' => 20],
            ['name' => 'Landazuri', 'departament_Id' => 20],
            ['name' => 'La Paz', 'departament_Id' => 20],
            ['name' => 'Lebrija', 'departament_Id' => 20],
            ['name' => 'Los Santos', 'departament_Id' => 20],
            ['name' => 'Macaravita', 'departament_Id' => 20],
            ['name' => 'Malaga', 'departament_Id' => 20],
            ['name' => 'Matanza', 'departament_Id' => 20],
            ['name' => 'Mogotes', 'departament_Id' => 20],
            ['name' => 'Molagavita', 'departament_Id' => 20],
            ['name' => 'Ocamonte', 'departament_Id' => 20],
            ['name' => 'Oiba', 'departament_Id' => 20],
            ['name' => 'Onzaga', 'departament_Id' => 20],
            ['name' => 'Palmar', 'departament_Id' => 20],
            ['name' => 'Palmas Del Socorro', 'departament_Id' => 20],
            ['name' => 'Paramo', 'departament_Id' => 20],
            ['name' => 'Piedecuesta', 'departament_Id' => 20],
            ['name' => 'Pinchote', 'departament_Id' => 20],
            ['name' => 'Puente Nacional', 'departament_Id' => 20],
            ['name' => 'Puerto Parra', 'departament_Id' => 20],
            ['name' => 'Puerto Wilches', 'departament_Id' => 20],
            ['name' => 'Rionegro', 'departament_Id' => 20],
            ['name' => 'Sabana De Torres', 'departament_Id' => 20],
            ['name' => 'San Andres', 'departament_Id' => 20],
            ['name' => 'San Benito', 'departament_Id' => 20],
            ['name' => 'San Gil', 'departament_Id' => 20],
            ['name' => 'San Joaquin', 'departament_Id' => 20],
            ['name' => 'San Jose De Miranda', 'departament_Id' => 20],
            ['name' => 'San Miguel', 'departament_Id' => 20],
            ['name' => 'San Vicente De Chucuri', 'departament_Id' => 20],
            ['name' => 'Santa Barbara', 'departament_Id' => 20],
            ['name' => 'Santa Helena Del Opon', 'departament_Id' => 20],
            ['name' => 'Simacota', 'departament_Id' => 20],
            ['name' => 'Socorro', 'departament_Id' => 20],
            ['name' => 'Suaita', 'departament_Id' => 20],
            ['name' => 'Sucre', 'departament_Id' => 20],
            ['name' => 'Surata', 'departament_Id' => 20],
            ['name' => 'Tona', 'departament_Id' => 20],
            ['name' => 'Valle De San Jose', 'departament_Id' => 20],
            ['name' => 'Velez', 'departament_Id' => 20],
            ['name' => 'Vetas', 'departament_Id' => 20],
            ['name' => 'Villanueva', 'departament_Id' => 20],
            ['name' => 'Zapatoca', 'departament_Id' => 20],
            ['name' => 'Sincelejo', 'departament_Id' => 21],
            ['name' => 'Buenavista', 'departament_Id' => 21],
            ['name' => 'Caimito', 'departament_Id' => 21],
            ['name' => 'Coloso', 'departament_Id' => 21],
            ['name' => 'Corozal', 'departament_Id' => 21],
            ['name' => 'Coveñas', 'departament_Id' => 21],
            ['name' => 'Chalan', 'departament_Id' => 21],
            ['name' => 'El Roble', 'departament_Id' => 21],
            ['name' => 'Galeras', 'departament_Id' => 21],
            ['name' => 'Guaranda', 'departament_Id' => 21],
            ['name' => 'La Union', 'departament_Id' => 21],
            ['name' => 'Los Palmitos', 'departament_Id' => 21],
            ['name' => 'Majagual', 'departament_Id' => 21],
            ['name' => 'Morroa', 'departament_Id' => 21],
            ['name' => 'Ovejas', 'departament_Id' => 21],
            ['name' => 'Palmito', 'departament_Id' => 21],
            ['name' => 'Sampues', 'departament_Id' => 21],
            ['name' => 'San Benito Abad', 'departament_Id' => 21],
            ['name' => 'San Juan De Betulia', 'departament_Id' => 21],
            ['name' => 'San Marcos', 'departament_Id' => 21],
            ['name' => 'San Onofre', 'departament_Id' => 21],
            ['name' => 'San Pedro', 'departament_Id' => 21],
            ['name' => 'San Luis De Since', 'departament_Id' => 21],
            ['name' => 'Sucre', 'departament_Id' => 21],
            ['name' => 'Santiago De Tolu', 'departament_Id' => 21],
            ['name' => 'Tolu Viejo', 'departament_Id' => 21],
            ['name' => 'Ibague', 'departament_Id' => 22],
            ['name' => 'Alpujarra', 'departament_Id' => 22],
            ['name' => 'Alvarado', 'departament_Id' => 22],
            ['name' => 'Ambalema', 'departament_Id' => 22],
            ['name' => 'Anzoategui', 'departament_Id' => 22],
            ['name' => 'Armero', 'departament_Id' => 22],
            ['name' => 'Ataco', 'departament_Id' => 22],
            ['name' => 'Cajamarca', 'departament_Id' => 22],
            ['name' => 'Carmen De Apicala', 'departament_Id' => 22],
            ['name' => 'Casabianca', 'departament_Id' => 22],
            ['name' => 'Chaparral', 'departament_Id' => 22],
            ['name' => 'Coello', 'departament_Id' => 22],
            ['name' => 'Coyaima', 'departament_Id' => 22],
            ['name' => 'Cunday', 'departament_Id' => 22],
            ['name' => 'Dolores', 'departament_Id' => 22],
            ['name' => 'Espinal', 'departament_Id' => 22],
            ['name' => 'Falan', 'departament_Id' => 22],
            ['name' => 'Flandes', 'departament_Id' => 22],
            ['name' => 'Fresno', 'departament_Id' => 22],
            ['name' => 'Guamo', 'departament_Id' => 22],
            ['name' => 'Herveo', 'departament_Id' => 22],
            ['name' => 'Honda', 'departament_Id' => 22],
            ['name' => 'Icononzo', 'departament_Id' => 22],
            ['name' => 'Lerida', 'departament_Id' => 22],
            ['name' => 'Libano', 'departament_Id' => 22],
            ['name' => 'Mariquita', 'departament_Id' => 22],
            ['name' => 'Melgar', 'departament_Id' => 22],
            ['name' => 'Murillo', 'departament_Id' => 22],
            ['name' => 'Natagaima', 'departament_Id' => 22],
            ['name' => 'Ortega', 'departament_Id' => 22],
            ['name' => 'Palocabildo', 'departament_Id' => 22],
            ['name' => 'Piedras', 'departament_Id' => 22],
            ['name' => 'Planadas', 'departament_Id' => 22],
            ['name' => 'Prado', 'departament_Id' => 22],
            ['name' => 'Purificacion', 'departament_Id' => 22],
            ['name' => 'Rioblanco', 'departament_Id' => 22],
            ['name' => 'Roncesvalles', 'departament_Id' => 22],
            ['name' => 'Rovira', 'departament_Id' => 22],
            ['name' => 'Saldaña', 'departament_Id' => 22],
            ['name' => 'San Antonio', 'departament_Id' => 22],
            ['name' => 'San Luis', 'departament_Id' => 22],
            ['name' => 'Santa Isabel', 'departament_Id' => 22],
            ['name' => 'Suarez', 'departament_Id' => 22],
            ['name' => 'Valle De San Juan', 'departament_Id' => 22],
            ['name' => 'Venadillo', 'departament_Id' => 22],
            ['name' => 'Villahermosa', 'departament_Id' => 22],
            ['name' => 'Villarrica', 'departament_Id' => 22],
            ['name' => 'Cali', 'departament_Id' => 23],
            ['name' => 'Alcala', 'departament_Id' => 23],
            ['name' => 'Andalucia', 'departament_Id' => 23],
            ['name' => 'Ansermanuevo', 'departament_Id' => 23],
            ['name' => 'Argelia', 'departament_Id' => 23],
            ['name' => 'Bolivar', 'departament_Id' => 23],
            ['name' => 'Buenaventura', 'departament_Id' => 23],
            ['name' => 'Guadalajara De Buga', 'departament_Id' => 23],
            ['name' => 'Bugalagrande', 'departament_Id' => 23],
            ['name' => 'Caicedonia', 'departament_Id' => 23],
            ['name' => 'Calima', 'departament_Id' => 23],
            ['name' => 'Candelaria', 'departament_Id' => 23],
            ['name' => 'Cartago', 'departament_Id' => 23],
            ['name' => 'Dagua', 'departament_Id' => 23],
            ['name' => 'El Aguila', 'departament_Id' => 23],
            ['name' => 'El Cairo', 'departament_Id' => 23],
            ['name' => 'El Cerrito', 'departament_Id' => 23],
            ['name' => 'El Dovio', 'departament_Id' => 23],
            ['name' => 'Florida', 'departament_Id' => 23],
            ['name' => 'Ginebra', 'departament_Id' => 23],
            ['name' => 'Guacari', 'departament_Id' => 23],
            ['name' => 'Jamundi', 'departament_Id' => 23],
            ['name' => 'La Cumbre', 'departament_Id' => 23],
            ['name' => 'La Union', 'departament_Id' => 23],
            ['name' => 'La Victoria', 'departament_Id' => 23],
            ['name' => 'Obando', 'departament_Id' => 23],
            ['name' => 'Palmira', 'departament_Id' => 23],
            ['name' => 'Pradera', 'departament_Id' => 23],
            ['name' => 'Restrepo', 'departament_Id' => 23],
            ['name' => 'Riofrio', 'departament_Id' => 23],
            ['name' => 'Roldanillo', 'departament_Id' => 23],
            ['name' => 'San Pedro', 'departament_Id' => 23],
            ['name' => 'Sevilla', 'departament_Id' => 23],
            ['name' => 'Toro', 'departament_Id' => 23],
            ['name' => 'Trujillo', 'departament_Id' => 23],
            ['name' => 'Tulua', 'departament_Id' => 23],
            ['name' => 'Ulloa', 'departament_Id' => 23],
            ['name' => 'Versalles', 'departament_Id' => 23],
            ['name' => 'Vijes', 'departament_Id' => 23],
            ['name' => 'Yotoco', 'departament_Id' => 23],
            ['name' => 'Yumbo', 'departament_Id' => 23],
            ['name' => 'Zarzal', 'departament_Id' => 23],
            ['name' => 'Arauca', 'departament_Id' => 23],
            ['name' => 'Arauquita', 'departament_Id' => 23],
            ['name' => 'Cravo Norte', 'departament_Id' => 23],
            ['name' => 'Fortul', 'departament_Id' => 23],
            ['name' => 'Puerto Rondon', 'departament_Id' => 23],
            ['name' => 'Saravena', 'departament_Id' => 23],
            ['name' => 'Tame', 'departament_Id' => 23],
            ['name' => 'Yopal', 'departament_Id' => 25],
            ['name' => 'Arauca', 'departament_Id' => 24],
            ['name' => 'Arauquita', 'departament_Id' => 24],
            ['name' => 'Cravo Norte', 'departament_Id' => 24],
            ['name' => 'Fortul', 'departament_Id' => 24],
            ['name' => 'Puerto Rondon', 'departament_Id' => 24],
            ['name' => 'Saravena', 'departament_Id' => 24],
            ['name' => 'Tame', 'departament_Id' => 24],
            ['name' => 'Aguazul', 'departament_Id' => 25],
            ['name' => 'Chameza', 'departament_Id' => 25],
            ['name' => 'Hato Corozal', 'departament_Id' => 25],
            ['name' => 'La Salina', 'departament_Id' => 25],
            ['name' => 'Mani', 'departament_Id' => 25],
            ['name' => 'Monterrey', 'departament_Id' => 25],
            ['name' => 'Nunchia', 'departament_Id' => 25],
            ['name' => 'Orocue', 'departament_Id' => 25],
            ['name' => 'Paz De Ariporo', 'departament_Id' => 25],
            ['name' => 'Pore', 'departament_Id' => 25],
            ['name' => 'Recetor', 'departament_Id' => 25],
            ['name' => 'Sabanalarga', 'departament_Id' => 25],
            ['name' => 'Sacama', 'departament_Id' => 25],
            ['name' => 'San Luis De Palenque', 'departament_Id' => 25],
            ['name' => 'Tamara', 'departament_Id' => 25],
            ['name' => 'Tauramena', 'departament_Id' => 25],
            ['name' => 'Trinidad', 'departament_Id' => 25],
            ['name' => 'Villanueva', 'departament_Id' => 25],
            ['name' => 'Mocoa', 'departament_Id' => 26],
            ['name' => 'Colon', 'departament_Id' => 26],
            ['name' => 'Orito', 'departament_Id' => 26],
            ['name' => 'Puerto Asis', 'departament_Id' => 26],
            ['name' => 'Puerto Caicedo', 'departament_Id' => 26],
            ['name' => 'Puerto Guzman', 'departament_Id' => 26],
            ['name' => 'Leguizamo', 'departament_Id' => 26],
            ['name' => 'Sibundoy', 'departament_Id' => 26],
            ['name' => 'San Francisco', 'departament_Id' => 26],
            ['name' => 'San Miguel', 'departament_Id' => 26],
            ['name' => 'Santiago', 'departament_Id' => 26],
            ['name' => 'Valle Del Guamuez', 'departament_Id' => 26],
            ['name' => 'Villagarzon', 'departament_Id' => 26],
            ['name' => 'San Andres', 'departament_Id' => 27],
            ['name' => 'Providencia', 'departament_Id' => 27],
            ['name' => 'Leticia', 'departament_Id' => 28],
            ['name' => 'El Encanto', 'departament_Id' => 28],
            ['name' => 'La Chorrera', 'departament_Id' => 28],
            ['name' => 'La Pedrera', 'departament_Id' => 28],
            ['name' => 'La Victoria', 'departament_Id' => 28],
            ['name' => 'Miriti', 'departament_Id' => 28],
            ['name' => 'Puerto Alegria', 'departament_Id' => 28],
            ['name' => 'Puerto Arica', 'departament_Id' => 28],
            ['name' => 'Puerto Nariño', 'departament_Id' => 28],
            ['name' => 'Puerto Santander', 'departament_Id' => 28],
            ['name' => 'Tarapaca', 'departament_Id' => 28],
            ['name' => 'Inirida', 'departament_Id' => 29],
            ['name' => 'Barranco Minas', 'departament_Id' => 29],
            ['name' => 'Mapiripana', 'departament_Id' => 29],
            ['name' => 'San Felipe', 'departament_Id' => 29],
            ['name' => 'Puerto Colombia', 'departament_Id' => 29],
            ['name' => 'La Guadalupe', 'departament_Id' => 29],
            ['name' => 'Cacahual', 'departament_Id' => 29],
            ['name' => 'Pana Pana', 'departament_Id' => 29],
            ['name' => 'Morichal', 'departament_Id' => 29],
            ['name' => 'San Jose Del Guaviare', 'departament_Id' => 30],
            ['name' => 'Calamar', 'departament_Id' => 30],
            ['name' => 'El Retorno', 'departament_Id' => 30],
            ['name' => 'Miraflores', 'departament_Id' => 30],
            ['name' => 'Mitu', 'departament_Id' => 31],
            ['name' => 'Caruru', 'departament_Id' => 31],
            ['name' => 'Pacoa', 'departament_Id' => 31],
            ['name' => 'Taraira', 'departament_Id' => 31],
            ['name' => 'Papunaua', 'departament_Id' => 31],
            ['name' => 'Yavarate', 'departament_Id' => 31],
            ['name' => 'Puerto Carreño', 'departament_Id' => 32],
            ['name' => 'La Primavera', 'departament_Id' => 32],
            ['name' => 'Santa Rosalia', 'departament_Id' => 32],
            ['name' => 'Cumaribo', 'departament_Id' => 32],
        ];
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->municipalitys as $municipality) {

            Municipality::create([
                'department_id' => $municipality["departament_Id"],
                'name' => $municipality["name"],
            ]);
        }
    }
}
